/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DarkCoffee;
//just a test1
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public int someLibraryMethod() {
        return 10;
    }
}
