/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DarkCoffee;

//test one 
public class Library {
    public boolean someLibraryMethod() {
    	//Test two
        return true;
    }
}
